### ISSUE TITLE
Consolidate Email Signup Options

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1702]
On the [Preferences page](https://www.topcoder.com/settings/preferences), please remove the following lines and their switch:

- General Newsletter
- iOS Newsletter
- TCO Newsletter
- Predix Newsletter
- Cognitive Newsletter

@ajefts

**Comment by ajefts** [comment]
@urwithat can you get this one done for us?

**Comment by urwithat** [comment]
Sure @ajefts

**Comment by urwithat** [comment]
@dedywahyudi - Let us know when you push the changes to Dev

**Comment by dedywahyudi** [comment]
@urwithat This is the PR, need merged with DEV
https://github.com/topcoder-platform/community-app/pull/1704

**Comment by urwithat** [comment]
I've merged the PR

**Comment by ajefts** [comment]
@dedywahyudi @urwithat It looks like the front end is not updating the state of the switch when it's saved.  I need to refresh the page to get the UI to reflect the current state of the preference.

**Comment by ThomasKranitsas** [comment]
@ajefts I just tried in prod and it seems like the API is timing out (`504 Gateway Timeout Error`) thus the UI stucks in the same state.

Indeed, when refreshing the page, the preferences are saved.
Maybe the API is broken and doesn't `return` any response?

**Comment by ThomasKranitsas** [comment]
<img width="1399" alt="screenshot 2018-10-19 at 22 02 59" src="https://user-images.githubusercontent.com/4612921/47238408-c6727d00-d3ea-11e8-926a-b568a6d7decd.png">

**Comment by nithyaasworld** [comment]
Requirement stated in the description of this ticket has been fulfilled.

But the issue stated here https://github.com/topcoder-platform/community-app/issues/1702#issuecomment-431465939 is still present. I will raise a new ticket to address this.
